### ISSUE TITLE
[Assignment] 새싹 65일차 과제

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/SeSAC_Assignments#14]
### 과제 설명
- SwiftUI로 뷰를 그리는 연습을 해봅니다

### Todos
- [ ] 제시된 4개의 화면 만들어보기
- [ ] 뷰 내부적으로 몇가지 로직들 구현하기
- [ ] Navigation, Sheet등의 기능을 구현합니다
