### ISSUE TITLE
[Assignment] 새싹 26일차 과제

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/SeSAC_Assignments#4]
### 과제 설명
하나의 뷰컨트롤러에서 여러 API 통신을 진행해봅니다

### Todos
- [ ] 비슷한 영화 또는 드라마 정보 보여주기
- [ ] 추천 영화 또는 드라마 정보 보여주기
- [ ] 영화 포스터 / 배경 정보 보여주기
