### ISSUE TITLE
[Feat] CompositionalLayout 연습(with 8일차 Assignment)

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/SeSAC_Assignments#6]
### 과제 설명
Compositional Layout에 대한 연습을 8일차 과제로 진행합니다.

### Todos
- [ ] 집중모드의 UI를 Compositional Layout으로 구현해봅니다
- [ ] 설정의 UI를 CompositionalLayout으로 구현해봅니다
- [ ] 쇼핑 화면의 UI를 CompositionalLayout으로 구현해봅니다
- [ ] UINavigation.Appearance를 이용하여 NaivgaitonBar의 UI를 변경해봅니다
